nsqio/go-nsq

consumer.go
producer.go

I'm guessing this is user error, but I'm getting a panic when stopping a consumer as of this commit: 4e74fa1f8933064a4f04786e65d3ee7b611be598. Reading the comment in there, I'm trying to understand what's going on.
My shutdown code looks something like this:
```go
func (n *NSQPeer) Teardown() {
n.producer.Stop()
if n.consumer != nil {
n.consumer.DisconnectFromNSQD(n.host)
n.consumer.Stop()
<-n.consumer.StopChan
}
}
```
Here's the error:
```
runtime.panic(0x509600, 0x84c1d5)
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/bitly/go-nsq.(*Consumer).exit(0xc20800ef00)
/Users/tylertreat/Go/src/github.com/bitly/go-nsq/consumer.go:1082 +0x2e
github.com/bitly/go-nsq.func·007()
/Users/tylertreat/Go/src/github.com/bitly/go-nsq/consumer.go:990 +0x29
created by …
```

panic: runtime error: close of closed channel

---

config.go
config_test.go

- Matches nsqd's -tls-min-version flag format, which was changed in bitly/nsqd#518
- Defaults tls min version to TLS1.0
- Sets tls max version to enable TLS_FALLBACK_SCSV prior to Go 1.5
- see https://go-review.googlesource.com/#/c/1776/ (thanks @jehiah)

tls updates: match nsqd min version flag, set default max/min (per #101)

---

consumer.go

When specifying `nsqd` addresses directly, upon reconnecting, the address was being duplicated in `nsqdTCPAddrs`

consumer: Only add host address once on connection.

---

consumer.go

This fixes the following scenario:
1. Consumer is connected to one NSQD host using ConnectToNSQD.
2. Consumer receives message and handler returns an error.
3. Consumer backs off.
4. DisconnectFromNSQD called before backoff closure wakes up.
5. Backoff closure wakes up, sees no connections, returns.
6. Consumer connects to NSQD host using ConnectToNSQD.
7. backoffCounter still > 0 so never sends RDY count (in
maybeUpdateRDY).
8. Consumer is now stuck and never sends RDY > 0.

consumer: Reset backoff counter when no connections left.

---

consumer.go

When removing lookupds, `r.lookupdQueryIndex` may become greater than `len(r.lookupdHTTPAddrs)`. This can cause a panic by index out of bounds error.

Fix bounds err when removing lookupds

---

consumer.go

nsq_to_nsq unexpectedly quit, and I have copious logs:
nsq_to_nsq run file:
```
#!/bin/sh
exec 2>&1
export GOMAXPROCS=2
exec chpst -u nsq:nsq /opt/nsq/bin/nsq_to_nsq \
-topic=logs \
-destination-topic=logs \
-destination-nsqd-tcp-address=this.is.a.cname.net:543 \
-nsqd-tcp-address=localhost:543 \
-channel=nsq_to_nsq \
-consumer-opt=tls_root_ca_file,/opt/nsq/certs/ca-cert.pem \
-consumer-opt=tls_cert,/opt/nsq/certs/client-cert.pem \
-consumer-opt=tls_key,/opt/nsq/certs/client-key.pem \
-consumer-opt=tls_v1,true \
-producer-opt=tls_root_ca_file,/opt/nsq/certs/ca-cert.pem \
-producer-opt=tls_cert,/opt/nsq/certs/client-cert.pem \
-producer-opt=tls_key,/opt/nsq/certs/client-key.pem \
-producer-opt=tls_v1,true \
-producer-opt=tls_min_version,tls1.2
```
nsqd run file:
```
#!/bin/sh
exec 2>&1 …
```

consumer: resolved addresses and reconnects

---

conn.go
consumer.go
producer.go

producer: log method has potential for edge case race condition
(checking nil then using); logger/logLvl could be set anytime, added
Lock in SetLogger, RLock in log and connect methods
producer: remove unnecessary continue in transactionCleanup for select

producer/consumer: clean up logging races

---

consumer.go

ticker starts when it's created. when it's created before waiting on jitter the jitter has no effect, unless jitter is greater than the tick interval.
example:
start := time.Now()
ticker := time.NewTicker(1500 * time.Millisecond)
time.Sleep(1000 * time.Millisecond)
<-ticker.C
fmt.Println(time.Now().Sub(start))
original PR was closed with rebase (oops) https://github.com/bitly/go-nsq/pull/113

consumer: jitter might have no effect

---

consumer.go

see above if statement: if ok || pendingOk { r.mtx.Unlock() return ErrAlreadyConnected }

remove unnecessary check on pendingOk

---

message.go

there was the possibility of a race since we were separately checking/storing
cc @schmichael

message: atomic races

---

command_test.go
mock_test.go
producer.go
producer_test.go

There's no reason for `transactionChan` to be unbuffered, it forces
the `router()` goroutine to work in lock-step with publishing, slowing
things down.
I should probably do some benchmarks.
cc @jehiah

producer: buffer transaction chan

---

producer.go
producer_test.go

Adds a Ping method to the Producer, which allows for testing a Producer's nsqd connection w/o publishing any messages to a topic. 
I've found it to be useful for failing fast when configuring Producers that might not Publish immediately (since otherwise, the connections are only made lazily on Publish).
Not thrilled with the method name "Ping", so am totally open to other suggestions.

producer: Adds a Ping method in order to validate an nsqd connection

---

config.go
config_test.go
conn.go
consumer_test.go
producer_test.go

For security reasons it would be great to support such feature as
binding outbound address, so nsqd could be firewalled on accepting
certain addresses, that reasonable in case when nsq-consumers or
producers are placed on machines with multiple interfaces.

Bind outbound connection to address from configuration

---

config.go
config_test.go
consumer.go
consumer_test.go

refactoring of the work in #123
RFR @jehiah

consumer: backoff strategies

---

config.go
config_test.go

- Documents that go-nsq calls SetConfig on BackoffStrategy, allowing
implementors to use config values in their own Calculate implementation.
- Allows full_jitter and exponential strategies to be set via the
backoff_strategy flag.

Allow BackoffStrategy to be set via flag, document BackoffStrategy.SetConfig

---

consumer.go
errors.go

Backoff chooses a random connection and tries to update the ready status; however, if the connection is closing, updateRdy will return immediately, leaving the backoffCounter in a bad state. The side effect is that maybeUpdateRdy will never update the ready count due to the incorrect backoffCounter and the consumer will never again consume messages.

when in backoff, make sure that the chosen connection isn't closing

---

.travis.yml
conn.go
consumer.go
delegates.go
mock_test.go
test.sh

If a consumer is in backoff and attempts to recover with RDY 1 and then a message, but response with RequeueWithoutBackoff it will stall and not exit backoff. (failing test attached)
cc: @georgicodes

Consumer stall after RequeueWithoutBackoff

---

config.go
consumer.go
mock_test.go
producer_test.go

This fixes #130 and #131.
The scenario is:
* single connection
* in backoff
* resumes with RDY 1
* connection dies
* never sends RDY again
We were (correctly) setting the redistribute flag, but it was attempting
to redistribute without having any connections.
This fix ensures that if an external heuristic sets the redistribute flag
it won't run proceed unless there are connections.
RFR @jehiah
/cc @twmb @zhangdaoling

consumer: don't run redistribute without connections

---

producer.go

Prior to this change, it is possible for more than one goroutine to
check:
if atomic.LoadInt32(&w.state) != StateConnected {
...thereafter calling w.connect.  w.connect first grabs a lock on
w.guard, and then asserts that it be the only goroutine attempting a
connection:
if !atomic.CompareAndSwapInt32(&w.state, StateInit, StateConnected) {
return ErrNotConnected
}
This means if there are two parallel actions which attempt to initiate
the connection, one of them will return ErrNotConnected if the first
succesfully connected.

producer: fix connection race

---

config.go
conn.go
consumer.go
delegates.go
version.go

go vet, golint, fmt fix

---

config.go

- responsibility has been moved to Consumer startStopContinueBackoff
- see PR #147 and #142

update FullJitterStrategy Calculate to not bound by MaxBackoffDuration

---

config_flag.go
config_flag_test.go

This enables simpler integration between the `Config` struct and the `flag` package which will make example consumers from `nsq` easier to use outside of that repo.
RFR @mreiferson
cc: @Dieterbe

Simpler integration of config and the stdlib flag package

---

consumer.go

Currently there is a data race when a consumer hits a backoff condition and then resumes. The resume via time.AfterFunc gets called from a different goroutine.
Note: this could also have been solved using one of the existing mutexes  (r.mtx or r.backoffMtx).

Add mutex around rng *rand.Rand to avoid data race on resume

---

producer.go

Since a producer doesn't expose it's connection or send command
method, it might be beneficial to add helper functions for producer
related commands like DeferredPublish

producer: expose DeferredPublish command

---

producer_test.go

No ip binding check: more portable.

TestProducerConnection() now green on OSX. fixes #161.

---

message.go

see https://github.com/nsqio/go-nsq/issues/174#issuecomment-210256321
for more discussion and before and after

DecodeMessage: skip bytes Buffer, reducing alloc overhead

---

consumer.go

I noticed the following in my logs recently
```
2016/12/22 15:05:27 consumer.go:844: WRN    1 [chaunceys_log/notificationsd] backing off for %!f(int=0001) seconds
```
This fixes related messages to always use `%s` for time.Duration types for backoff log messages.
RFR @mreiferson

logging: fix 'backing off for x' message formatting

---

.travis.yml
conn.go

switch to golang/snappy

---

conn.go

when producer.Stop() EOF exception occur
```
2016/12/01 09:44:47 ERR  3856 (10.160.3.70:4150) IO error - EOF
2016/12/01 09:44:47 INF  3856 (10.160.3.70:4150) beginning close
2016/12/01 09:44:47 INF  3856 (10.160.3.70:4150) readLoop exiting
2016/12/01 09:44:47 INF  3856 (10.160.3.70:4150) breaking out of writeLoop
2016/12/01 09:44:47 INF  3856 (10.160.3.70:4150) writeLoop exiting
2016/12/01 09:44:47 INF  3856 stopping
2016/12/01 09:44:47 INF  3856 exiting router
```

fix producer Stop() EOF

---

config.go
conn.go
consumer.go

consumer: redistribute RDY when connections are active

---

api_request.go
conn.go
consumer.go
consumer_test.go

consumer: retry nsqlookupd queries

---

conn.go
consumer.go
consumer_test.go
mock_test.go

this addresses the issue reported in #222

consumer: cleanup RDY handling; fix pausing

---

.travis.yml
protocol.go

This PR adds pre check for msg size before `make` a slice. 
We have encountered a panic in `make([]byte, msgSize)` with `panic: runtime error: makeslice: len out of range`. We have bounded the max message size by 20MB. So, it seems that make function should not panic. 
I have test that when `make` with a negative length, `make` will panic with `panic: runtime error: makeslice: len out of range`.

check response message size is positive

---

doc.go
version.go

This PR adds a doc.go file that acts as a small HOWTO.
With this change the go doc will display examples of a consumer and producer at the top of the documentation.

Add high-level godoc for publisher and consumer

---

conn.go

Fixes #254 
I also ended up moving the net.SplitHostPort code up so if it failed we don't make a new tls.Config/clone for nothing.

TLS Config copy fix

---

conn.go
consumer.go
delegates.go
producer.go
producer_test.go

I’ve added support for using separate loggers for each level.  I tried to minimize the changes required to existing code and maintain as much backwards compatibility as I could.
The change required to existing code is the requirement to add a call to `SetLoggingLevel()` if the default level (`LogLevelInfo`) is not the desired level. Previously the call to `SetLogger()` would do this implicitly.
This change also expands the API surface by 1 with a convenience function `SetLoggerForLevels()` that sets the same logger for the levels provided as parameters. This convenience function simplifies achieving the previous behavior of using just one logger for all levels.

Added support for setting logger for each log level

---

consumer.go
mock_test.go

This PR will reduct duplicate rdy update requests.

reduce duplicate rdy update requests

---

consumer.go
producer.go

```c.assertInitialized()```  is executed twice both in  ``` NewProducer() / NewConsumer() ```  and ```config.Validate()```

remove duplicate 'Config.assertInitialized()' check

---

AUTHORS

Going to update `nsq` and `pynsq` repos to follow this format as well, instead of copying around the README blob.

*: add AUTHORS file

---

doc.go

inspired by #306 
cc @jehiah @mreiferson

docs: add exit-on-signal and more comments to example consumer

---

api_request.go
config.go
consumer.go
consumer_test.go

The [`AUTH` protocol spec](https://nsq.io/clients/tcp_protocol_spec.html#auth)  and [nsqd AUTH details](https://nsq.io/components/nsqd.html#auth) don't give much guidance for how to use AUTH with a lookupd endpoint (except implying that [`nsqauthfilter`](https://github.com/jehiah/nsqauth-contrib#nsqauthfilter) is one approach).
Currently the only exposed capability to use a lookup endpoint that requires authorization is to bake authorization credentials into the URL used as a lookup endpoint. go-nsq then makes a GET request to that endpoint during discovery.
Security best practice is to move authorization details to a header and out of the URL i.e. a `Authorization: Bearer {Auth Secret}` header.
This issue is to introduce new behavior where an AuthSecret when set is used as a Bearer token …

Use AuthSecret as Bearer token for lookupd queries

---

producer.go

Removing empty switch case makes the code more readable.
See https://github.com/nsqio/go-nsq/pull/310#discussion_r517885032

producer: improve code readability

---

consumer.go

The code can panic if invalid lookupd address is provided:
panic: parse "http:// myhostname:4161": invalid character " " in host name
This is caused different validation of the input when configured
in ConnectToNSQLookupd and when used in nextLookupdEndpoint.
Moving preparation of the URL to the beginning so that we don't
need to do any input validation in nextLookupEndpoint.
Fixes https://github.com/nsqio/go-nsq/issues/316

consumer: fix panic in nextLookupdEndpoint

---

producer.go

This corner case generally should not happen, but a nsqd bug or
strange network condition could possibly send erroneous bytes that
are interpreted as a response. The Producer should be robust,
and not panic the whole process.
fixes #345 (hopefully)

producer: handle case of no transactions in popTransaction()

---

config.go
conn.go
producer_test.go
protocol.go

- Add MaxMsgSize to configuration mimicking the nsqd cofiguration key. It defaults to 1048576 as the nsqd config -- source: https://github.com/nsqio/nsq/blob/a4939964f6715edd27a6904b87c2f9eb6a45e749/nsqd/options.go#L130
- Pass MaxMsgSize to ReadResponse via its caller, ReadUnpackedResponse. Check msgSize does not exceed the maximum in ReadResponse. This reduces the risk of attempting to read arbitrary (non-nsq) responses.
- Generate custom error if msgSize is the result of deserializing the first 4 bytes of an HTTP response (1213486160) to facilitate troublehooting
Fixes #352

Limit read message size

---

config.go
conn.go

This supports nsqio/nsq#1300 by providing a way to send topology information to nsqd

Set topology region+zone and send in IDENTIFY msg
